<robot name="offset_diff_drive" xmlns:xacro="http://ros.org/wiki/xacro">
    <xacro:property name="wheel_width" value="0.03" />
    <xacro:property name="wheel_radius" value="0.04" />

    <xacro:property name="wheel_separation" value="0.2" />
    <xacro:property name="wheel_offset" value="0.1" />

    <link name="base_link" />

    <joint name="base_joint" type="fixed">
        <origin xyz="0 0 ${wheel_radius + wheel_radius + 0.01 + 0.01}" rpy="0 0 0" />
        <axis xyz="0.0 0.0 1.0" />
        <parent link="base_link" />
        <child link="steer_base" />
    </joint>

    <link name="steer_base">
        <visual>
            <geometry>
                <box size="0.2 0.2 0.02" />
            </geometry>
        </visual>
        <collision>
            <geometry>
                <box size="0.2 0.2 0.02" />
            </geometry>
        </collision>
        <inertial>
            <mass value="0.1" />
            <origin xyz="0 0 0" />
            <inertia ixx="${0.1*(0.02*0.02+0.2*0.2)/12}" ixy="0" ixz="0" iyy="${0.1*(0.2*0.2+0.02*0.02)/12}" iyz="0" izz="${0.1*(0.2*0.2+0.2*0.2)/12}" />
        </inertial>
    </link>

    <joint name="steer_joint" type="continuous">
        <origin xyz="0 0 ${-wheel_radius - 0.01 - 0.01}" rpy="0 0 0" />
        <axis xyz="0.0 0.0 1.0" />
        <parent link="steer_base" />
        <child link="wheel_base" />
    </joint>

    <transmission name="steer_trans">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="steer_joint">
            <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
        </joint>
        <actuator name="steer_motor">
            <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
            <mechanicalReduction>1</mechanicalReduction>
        </actuator>
    </transmission>

    <link name="wheel_base">
        <visual>
            <geometry>
                <box size="0.15 0.15 0.02" />
            </geometry>
        </visual>
        <collision>
            <geometry>
                <box size="0.15 0.15 0.02" />
            </geometry>
        </collision>
        <inertial>
            <mass value="1" />
            <origin xyz="0 0 0" />
            <inertia ixx="${1*(0.02*0.02+0.15*0.15)/12}" ixy="0" ixz="0" iyy="${1*(0.15*0.15+0.02*0.02)/12}" iyz="0" izz="${1*(0.15*0.15+0.15*0.15)/12}" />
        </inertial>
    </link>

    <joint name="wheel_l_joint" type="continuous">
        <origin xyz="${-wheel_offset} ${wheel_separation/2} 0" rpy="0 0 0" />
        <axis xyz="0.0 1.0 0.0" />
        <limit effort="10" velocity="20" />
        <parent link="wheel_base" />
        <child link="wheel_l" />
    </joint>

    <transmission name="wheel_l_trans">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="wheel_l_joint">
            <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
        </joint>
        <actuator name="wheel_l_motor">
            <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
            <mechanicalReduction>1</mechanicalReduction>
        </actuator>
    </transmission>

    <link name="wheel_l">
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="${pi/2} 0.0 0.0" />
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_width}" />
            </geometry>
        </visual>
        <collision>
            <origin xyz="0.0 0.0 0.0" rpy="${pi/2} 0.0 0.0" />
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_width}" />
            </geometry>
        </collision>
        <inertial>
            <mass value="0.5" />
            <origin xyz="0 0 0" />
            <inertia ixx="${0.5*(3*wheel_radius*wheel_radius+wheel_width*wheel_width)/12}" ixy="0" ixz="0" iyy="${0.5*wheel_radius*wheel_radius/2}" iyz="0" izz="${0.5*(3*wheel_radius*wheel_radius+wheel_width*wheel_width)/12}" />
        </inertial>
    </link>

    <gazebo reference="wheel_l">
        <kp>1000000.0</kp>
        <kd>10.0</kd>
        <mu1>100.0</mu1>
        <mu2>100.0</mu2>
        <fdir1>1 0 0</fdir1>
        <maxVel>1.0</maxVel>
        <minDepth>0.00</minDepth>
    </gazebo>

    <joint name="wheel_r_joint" type="continuous">
        <origin xyz="${-wheel_offset} ${-wheel_separation/2} 0" rpy="0 0 0" />
        <axis xyz="0.0 1.0 0.0" />
        <limit effort="10" velocity="20" />
        <parent link="wheel_base" />
        <child link="wheel_r" />
    </joint>

    <transmission name="wheel_r_trans">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="wheel_r_joint">
            <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
        </joint>
        <actuator name="wheel_r_motor">
            <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
            <mechanicalReduction>1</mechanicalReduction>
        </actuator>
    </transmission>

    <link name="wheel_r">
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="${pi/2} 0.0 0.0" />
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_width}" />
            </geometry>
        </visual>
        <collision>
            <origin xyz="0.0 0.0 0.0" rpy="${pi/2} 0.0 0.0" />
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_width}" />
            </geometry>
        </collision>
        <inertial>
            <mass value="0.5" />
            <origin xyz="0 0 0" />
            <inertia ixx="${0.5*(3*wheel_radius*wheel_radius+wheel_width*wheel_width)/12}" ixy="0" ixz="0" iyy="${0.5*wheel_radius*wheel_radius/2}" iyz="0" izz="${0.5*(3*wheel_radius*wheel_radius+wheel_width*wheel_width)/12}" />
        </inertial>
    </link>

    <gazebo reference="wheel_r">
        <kp>1000000.0</kp>
        <kd>10.0</kd>
        <mu1>100.0</mu1>
        <mu2>100.0</mu2>
        <fdir1>1 0 0</fdir1>
        <maxVel>1.0</maxVel>
        <minDepth>0.00</minDepth>
    </gazebo>

    <joint name="caster_joint" type="fixed">
        <origin xyz="${wheel_offset} 0 0" rpy="0 0 0" />
        <parent link="wheel_base" />
        <child link="caster" />
    </joint>

    <link name="caster">
        <visual>
            <geometry>
                <sphere radius="${wheel_radius}" />
            </geometry>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${wheel_radius}" />
            </geometry>
        </collision>
        <inertial>
            <mass value="0.2" />
            <origin xyz="0 0 0" />
            <inertia ixx="${2*0.2*wheel_radius*wheel_radius/5}" ixy="0" ixz="0" iyy="${2*0.2*wheel_radius*wheel_radius/5}" iyz="0" izz="${2*0.2*wheel_radius*wheel_radius/5}" />
        </inertial>
    </link>

    <gazebo reference="caster">
        <kp>1000000.0</kp>
        <kd>10.0</kd>
        <mu1>0.0</mu1>
        <mu2>0.0</mu2>
        <maxVel>1.0</maxVel>
        <minDepth>0.00</minDepth>
    </gazebo>

    <gazebo>
        <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
            <robotNamespace>/robot</robotNamespace>
        </plugin>
        <plugin name="p3d_base_controller" filename="libgazebo_ros_p3d.so">
            <frameName>map</frameName>
            <updateRate>50.0</updateRate>
            <bodyName>base_link</bodyName>
            <topicName>ground_truth/state</topicName>
        </plugin>
    </gazebo>
</robot>